INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100002, 4, null, null, null, '2019-02-12', '00:00:00', '2019-02-12 00:00:00.000000');
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100004, 6, null, null, '', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100006, 7, null, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100007, 8, 2007, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100008, 9, 2012, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100009, 10, null, null, '2424', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100010, 11, 2027, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100011, 12, null, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100012, 13, 2035, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100013, 14, null, null, '2424', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100014, 15, null, 10003, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100015, 16, null, 4114, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100016, 17, null, null, '2424', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100023, 4, null, null, null, '2019-02-12', '00:00:00', '2019-02-12 00:00:00.000000');
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100025, 6, null, null, '', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100027, 7, null, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100028, 8, 2007, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100029, 9, 2012, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100030, 10, null, null, '1313', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100031, 11, 2026, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100032, 12, null, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100033, 13, 2059, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100034, 14, null, null, '131', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100035, 15, null, 10000, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100036, 16, null, 4347, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100037, 17, null, null, '1313', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100044, 4, null, null, null, '2019-02-12', '00:00:00', '2019-02-12 00:00:00.000000');
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100046, 6, null, null, '', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100048, 7, null, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100049, 8, 2007, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100050, 9, 2013, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100051, 10, null, null, '1313', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100052, 11, 2027, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100053, 12, null, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100054, 13, 2036, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100055, 14, null, null, '1313', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100056, 15, null, 10001, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100057, 16, null, 4215, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100058, 17, null, null, '1313', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100065, 4, null, null, null, '2019-02-12', '00:00:00', '2019-02-12 00:00:00.000000');
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100067, 6, null, null, '', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100069, 7, null, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100070, 8, 2007, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100071, 9, 2012, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100072, 10, null, null, '32131', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100073, 11, 2027, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100074, 12, null, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100075, 13, 2046, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100076, 14, null, null, '1313', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100077, 15, null, 10017, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100078, 16, null, 4114, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100079, 17, null, null, '141', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100086, 4, null, null, null, '2019-02-12', '00:00:00', '2019-02-12 00:00:00.000000');
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100088, 6, null, null, '', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100090, 7, null, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100091, 8, 2007, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100092, 9, 2015, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100093, 10, null, null, '1313', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100094, 11, 2029, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100095, 12, null, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100096, 13, 2086, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100097, 14, null, null, '1313', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100098, 15, null, 10001, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100099, 16, null, 4104, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100100, 17, null, null, '1313', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100107, 4, null, null, null, '2019-02-12', '00:00:00', '2019-02-12 00:00:00.000000');
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100109, 6, null, null, '', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100111, 7, null, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100112, 8, 2007, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100113, 9, 2013, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100114, 10, null, null, '242', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100115, 11, 2026, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100116, 12, null, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100117, 13, 2068, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100118, 14, null, null, '2424', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100119, 15, null, 10002, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100120, 16, null, 4347, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100121, 17, null, null, '2424', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100126, 4, null, null, null, '2019-02-12', '00:00:00', '2019-02-12 00:00:00.000000');
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100128, 6, null, null, '', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100130, 7, null, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100131, 8, 2007, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100132, 9, 2012, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100133, 10, null, null, '2424', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100134, 11, 2027, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100135, 12, null, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100136, 13, 2035, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100137, 14, null, null, '2424', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100138, 15, null, 10003, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100139, 16, null, 4114, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100140, 17, null, null, '2424', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100142, 4, null, null, null, '2019-02-12', '00:00:00', '2019-02-12 00:00:00.000000');
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100144, 6, null, null, '', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100146, 7, null, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100147, 8, 2007, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100148, 9, 2012, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100149, 10, null, null, '2424', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100150, 11, 2027, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100151, 12, null, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100152, 13, 2035, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100153, 14, null, null, '2424', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100154, 15, null, 10003, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100155, 16, null, 4114, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100156, 17, null, null, '2424', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100158, 4, null, null, null, '2019-02-12', '00:00:00', '2019-02-12 00:00:00.000000');
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100160, 6, null, null, '', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100162, 7, null, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100163, 8, 2007, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100164, 9, 2012, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100165, 10, null, null, '1313', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100166, 11, 2026, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100167, 12, null, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100168, 13, 2059, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100169, 14, null, null, '131', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100170, 15, null, 10000, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100171, 16, null, 4347, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100172, 17, null, null, '1313', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100174, 4, null, null, null, '2019-02-12', '00:00:00', '2019-02-12 00:00:00.000000');
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100176, 6, null, null, '', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100178, 7, null, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100179, 8, 2007, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100180, 9, 2012, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100181, 10, null, null, '1313', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100182, 11, 2026, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100183, 12, null, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100184, 13, 2059, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100185, 14, null, null, '131', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100186, 15, null, 10000, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100187, 16, null, 4347, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100188, 17, null, null, '1313', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100190, 4, null, null, null, '2019-02-12', '00:00:00', '2019-02-12 00:00:00.000000');
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100192, 6, null, null, '', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100194, 7, null, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100195, 8, 2007, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100196, 9, 2013, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100197, 10, null, null, '1313', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100198, 11, 2027, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100199, 12, null, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100200, 13, 2036, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100201, 14, null, null, '1313', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100202, 15, null, 10001, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100203, 16, null, 4215, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100204, 17, null, null, '1313', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100206, 4, null, null, null, '2019-02-12', '00:00:00', '2019-02-12 00:00:00.000000');
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100208, 6, null, null, '', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100210, 7, null, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100211, 8, 2007, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100212, 9, 2013, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100213, 10, null, null, '1313', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100214, 11, 2027, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100215, 12, null, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100216, 13, 2036, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100217, 14, null, null, '1313', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100218, 15, null, 10001, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100219, 16, null, 4215, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100220, 17, null, null, '1313', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100224, 4, null, null, null, '2019-02-12', '00:00:00', '2019-02-12 00:00:00.000000');
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100226, 6, null, null, '', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100228, 7, null, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100229, 8, 2007, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100230, 9, 2013, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100231, 10, null, null, '144', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100232, 11, 2026, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100233, 12, null, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100234, 13, 2071, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100235, 14, null, null, '2424', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100236, 15, null, 10004, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100237, 16, null, 4092, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100238, 17, null, null, '2424', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100246, 4, null, null, null, '2019-02-12', '00:00:00', '2019-02-12 00:00:00.000000');
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100248, 6, null, null, '', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100250, 7, null, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100251, 8, 2007, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100252, 9, 2012, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100253, 10, null, null, '32131', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100254, 11, 2027, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100255, 12, null, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100256, 13, 2046, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100257, 14, null, null, '1313', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100258, 15, null, 10017, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100259, 16, null, 4114, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100260, 17, null, null, '141', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100262, 4, null, null, null, '2019-02-12', '00:00:00', '2019-02-12 00:00:00.000000');
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100264, 6, null, null, '', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100266, 7, null, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100267, 8, 2007, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100268, 9, 2012, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100269, 10, null, null, '32131', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100270, 11, 2027, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100271, 12, null, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100272, 13, 2046, null, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100273, 14, null, null, '1313', null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100274, 15, null, 10017, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100275, 16, null, 4114, null, null, null, null);
INSERT INTO esrd.valuedfield (id, field_id, catalogelem_id, value_int, value_str, value_date, value_time, value_datetime) VALUES (100276, 17, null, null, '141', null, null, null);

INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100006, 100007);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100006, 100008);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100006, 100009);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100006, 100010);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100006, 100011);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100006, 100012);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100006, 100013);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100006, 100014);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100006, 100015);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100006, 100016);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100027, 100028);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100027, 100029);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100027, 100030);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100027, 100031);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100027, 100032);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100027, 100033);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100027, 100034);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100027, 100035);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100027, 100036);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100027, 100037);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100048, 100049);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100048, 100050);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100048, 100051);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100048, 100052);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100048, 100053);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100048, 100054);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100048, 100055);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100048, 100056);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100048, 100057);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100048, 100058);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100069, 100070);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100069, 100071);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100069, 100072);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100069, 100073);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100069, 100074);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100069, 100075);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100069, 100076);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100069, 100077);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100069, 100078);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100069, 100079);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100090, 100091);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100090, 100092);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100090, 100093);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100090, 100094);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100090, 100095);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100090, 100096);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100090, 100097);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100090, 100098);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100090, 100099);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100090, 100100);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100111, 100112);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100111, 100113);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100111, 100114);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100111, 100115);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100111, 100116);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100111, 100117);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100111, 100118);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100111, 100119);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100111, 100120);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100111, 100121);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100130, 100131);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100130, 100132);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100130, 100133);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100130, 100134);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100130, 100135);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100130, 100136);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100130, 100137);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100130, 100138);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100130, 100139);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100130, 100140);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100146, 100147);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100146, 100148);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100146, 100149);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100146, 100150);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100146, 100151);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100146, 100152);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100146, 100153);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100146, 100154);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100146, 100155);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100146, 100156);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100162, 100163);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100162, 100164);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100162, 100165);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100162, 100166);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100162, 100167);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100162, 100168);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100162, 100169);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100162, 100170);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100162, 100171);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100162, 100172);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100178, 100179);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100178, 100180);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100178, 100181);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100178, 100182);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100178, 100183);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100178, 100184);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100178, 100185);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100178, 100186);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100178, 100187);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100178, 100188);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100194, 100195);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100194, 100196);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100194, 100197);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100194, 100198);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100194, 100199);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100194, 100200);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100194, 100201);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100194, 100202);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100194, 100203);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100194, 100204);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100210, 100211);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100210, 100212);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100210, 100213);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100210, 100214);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100210, 100215);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100210, 100216);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100210, 100217);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100210, 100218);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100210, 100219);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100210, 100220);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100228, 100229);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100228, 100230);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100228, 100231);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100228, 100232);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100228, 100233);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100228, 100234);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100228, 100235);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100228, 100236);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100228, 100237);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100228, 100238);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100250, 100251);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100250, 100252);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100250, 100253);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100250, 100254);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100250, 100255);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100250, 100256);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100250, 100257);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100250, 100258);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100250, 100259);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100250, 100260);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100266, 100267);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100266, 100268);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100266, 100269);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100266, 100270);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100266, 100271);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100266, 100272);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100266, 100273);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100266, 100274);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100266, 100275);
INSERT INTO esrd.valuedfield_child_valued_field (valued_field_id, child_valued_field_id) VALUES (100266, 100276);

INSERT INTO esrd.doc (id, doctype_id, reg_num, reg_datetime, project_reg_num, project_reg_datetime, insert_datetime, docstatus, url_pdf, initial_user_id, parent_doc_id) VALUES (100084, 1, null, null, 'согл-5/19', '2019-10-21 10:44:16.918000', '2019-10-21 10:44:16.918000', 'IN_AGREEMENT', 'resources/files/pdf/100084.pdf', 4194, null);
INSERT INTO esrd.doc (id, doctype_id, reg_num, reg_datetime, project_reg_num, project_reg_datetime, insert_datetime, docstatus, url_pdf, initial_user_id, parent_doc_id) VALUES (100105, 1, null, null, 'согл-6/19', '2019-10-21 10:45:26.919000', '2019-10-21 10:45:26.919000', 'IN_AGREEMENT', 'resources/files/pdf/100105.pdf', 4194, null);
INSERT INTO esrd.doc (id, doctype_id, reg_num, reg_datetime, project_reg_num, project_reg_datetime, insert_datetime, docstatus, url_pdf, initial_user_id, parent_doc_id) VALUES (100000, 1, 'ДПР-СЗ-1/19', '2019-10-21 12:43:30.147000', 'согл-1/19', '2019-10-21 10:40:56.165000', '2019-10-21 10:40:56.165000', 'IN_WORK', 'resources/files/pdf/100000.pdf', 4194, null);
INSERT INTO esrd.doc (id, doctype_id, reg_num, reg_datetime, project_reg_num, project_reg_datetime, insert_datetime, docstatus, url_pdf, initial_user_id, parent_doc_id) VALUES (100021, 1, 'ДПР-СЗ-2/19', '2019-10-21 12:43:45.913000', 'согл-2/19', '2019-10-21 10:41:51.697000', '2019-10-21 10:41:51.697000', 'IN_WORK', 'resources/files/pdf/100021.pdf', 4194, null);
INSERT INTO esrd.doc (id, doctype_id, reg_num, reg_datetime, project_reg_num, project_reg_datetime, insert_datetime, docstatus, url_pdf, initial_user_id, parent_doc_id) VALUES (100042, 1, 'ДПР-СЗ-3/19', '2019-10-21 12:44:05.827000', 'согл-3/19', '2019-10-21 10:42:22.415000', '2019-10-21 10:42:22.415000', 'IN_WORK', 'resources/files/pdf/100042.pdf', 4194, null);
INSERT INTO esrd.doc (id, doctype_id, reg_num, reg_datetime, project_reg_num, project_reg_datetime, insert_datetime, docstatus, url_pdf, initial_user_id, parent_doc_id) VALUES (100222, 1, null, null, 'согл-7/19', '2019-10-21 12:44:45.401000', '2019-10-21 12:44:45.402000', 'IN_AGREEMENT', 'resources/files/pdf/100222.pdf', 4000, null);
INSERT INTO esrd.doc (id, doctype_id, reg_num, reg_datetime, project_reg_num, project_reg_datetime, insert_datetime, docstatus, url_pdf, initial_user_id, parent_doc_id) VALUES (100063, 1, 'ДПР-СЗ-4/19', '2019-10-21 12:46:04.495000', 'согл-4/19', '2019-10-21 10:43:15.679000', '2019-10-21 10:43:15.679000', 'IN_WORK', 'resources/files/pdf/100063.pdf', 4194, null);

INSERT INTO esrd.doc_valuedfields (id, doc_id, valuedfield_id, position) VALUES (100085, 100084, 100086, 1);
INSERT INTO esrd.doc_valuedfields (id, doc_id, valuedfield_id, position) VALUES (100087, 100084, 100088, 2);
INSERT INTO esrd.doc_valuedfields (id, doc_id, valuedfield_id, position) VALUES (100089, 100084, 100090, 4);
INSERT INTO esrd.doc_valuedfields (id, doc_id, valuedfield_id, position) VALUES (100106, 100105, 100107, 1);
INSERT INTO esrd.doc_valuedfields (id, doc_id, valuedfield_id, position) VALUES (100108, 100105, 100109, 2);
INSERT INTO esrd.doc_valuedfields (id, doc_id, valuedfield_id, position) VALUES (100110, 100105, 100111, 4);
INSERT INTO esrd.doc_valuedfields (id, doc_id, valuedfield_id, position) VALUES (100143, 100000, 100142, 1);
INSERT INTO esrd.doc_valuedfields (id, doc_id, valuedfield_id, position) VALUES (100145, 100000, 100144, 2);
INSERT INTO esrd.doc_valuedfields (id, doc_id, valuedfield_id, position) VALUES (100157, 100000, 100146, 4);
INSERT INTO esrd.doc_valuedfields (id, doc_id, valuedfield_id, position) VALUES (100175, 100021, 100174, 1);
INSERT INTO esrd.doc_valuedfields (id, doc_id, valuedfield_id, position) VALUES (100177, 100021, 100176, 2);
INSERT INTO esrd.doc_valuedfields (id, doc_id, valuedfield_id, position) VALUES (100189, 100021, 100178, 4);
INSERT INTO esrd.doc_valuedfields (id, doc_id, valuedfield_id, position) VALUES (100207, 100042, 100206, 1);
INSERT INTO esrd.doc_valuedfields (id, doc_id, valuedfield_id, position) VALUES (100209, 100042, 100208, 2);
INSERT INTO esrd.doc_valuedfields (id, doc_id, valuedfield_id, position) VALUES (100221, 100042, 100210, 4);
INSERT INTO esrd.doc_valuedfields (id, doc_id, valuedfield_id, position) VALUES (100223, 100222, 100224, 1);
INSERT INTO esrd.doc_valuedfields (id, doc_id, valuedfield_id, position) VALUES (100225, 100222, 100226, 2);
INSERT INTO esrd.doc_valuedfields (id, doc_id, valuedfield_id, position) VALUES (100227, 100222, 100228, 4);
INSERT INTO esrd.doc_valuedfields (id, doc_id, valuedfield_id, position) VALUES (100263, 100063, 100262, 1);
INSERT INTO esrd.doc_valuedfields (id, doc_id, valuedfield_id, position) VALUES (100265, 100063, 100264, 2);
INSERT INTO esrd.doc_valuedfields (id, doc_id, valuedfield_id, position) VALUES (100277, 100063, 100266, 4);

INSERT INTO esrd.doc_agreement (id, ordering, doc_id, user_id, returned_user_id, agreed_datetime, comment, decision_type, final_user, cur_user) VALUES (100103, 1, 100084, 4373, null, null, null, null, false, true);
INSERT INTO esrd.doc_agreement (id, ordering, doc_id, user_id, returned_user_id, agreed_datetime, comment, decision_type, final_user, cur_user) VALUES (100104, 2, 100084, 4373, null, null, null, null, true, false);
INSERT INTO esrd.doc_agreement (id, ordering, doc_id, user_id, returned_user_id, agreed_datetime, comment, decision_type, final_user, cur_user) VALUES (100124, 1, 100105, 4373, null, null, null, null, false, true);
INSERT INTO esrd.doc_agreement (id, ordering, doc_id, user_id, returned_user_id, agreed_datetime, comment, decision_type, final_user, cur_user) VALUES (100125, 2, 100105, 4373, null, null, null, null, true, false);
INSERT INTO esrd.doc_agreement (id, ordering, doc_id, user_id, returned_user_id, agreed_datetime, comment, decision_type, final_user, cur_user) VALUES (100019, 1, 100000, 4193, null, '2019-10-21 12:43:26.240000', '', 'ACCEPTED', false, false);
INSERT INTO esrd.doc_agreement (id, ordering, doc_id, user_id, returned_user_id, agreed_datetime, comment, decision_type, final_user, cur_user) VALUES (100020, 2, 100000, 4329, null, '2019-10-21 12:43:32.507000', '', 'ACCEPTED', true, false);
INSERT INTO esrd.doc_agreement (id, ordering, doc_id, user_id, returned_user_id, agreed_datetime, comment, decision_type, final_user, cur_user) VALUES (100040, 1, 100021, 4193, null, '2019-10-21 12:43:42.255000', '', 'ACCEPTED', false, false);
INSERT INTO esrd.doc_agreement (id, ordering, doc_id, user_id, returned_user_id, agreed_datetime, comment, decision_type, final_user, cur_user) VALUES (100041, 2, 100021, 4329, null, '2019-10-21 12:43:48.071000', '', 'ACCEPTED', true, false);
INSERT INTO esrd.doc_agreement (id, ordering, doc_id, user_id, returned_user_id, agreed_datetime, comment, decision_type, final_user, cur_user) VALUES (100061, 1, 100042, 4193, null, '2019-10-21 12:44:02.078000', '', 'ACCEPTED', false, false);
INSERT INTO esrd.doc_agreement (id, ordering, doc_id, user_id, returned_user_id, agreed_datetime, comment, decision_type, final_user, cur_user) VALUES (100062, 2, 100042, 4329, null, '2019-10-21 12:44:07.911000', '', 'ACCEPTED', true, false);
INSERT INTO esrd.doc_agreement (id, ordering, doc_id, user_id, returned_user_id, agreed_datetime, comment, decision_type, final_user, cur_user) VALUES (100241, 1, 100222, 4373, null, null, null, null, false, true);
INSERT INTO esrd.doc_agreement (id, ordering, doc_id, user_id, returned_user_id, agreed_datetime, comment, decision_type, final_user, cur_user) VALUES (100242, 2, 100222, 4373, null, null, null, null, true, false);
INSERT INTO esrd.doc_agreement (id, ordering, doc_id, user_id, returned_user_id, agreed_datetime, comment, decision_type, final_user, cur_user) VALUES (100082, 1, 100063, 4193, null, '2019-10-21 12:46:00.699000', '', 'ACCEPTED', false, false);
INSERT INTO esrd.doc_agreement (id, ordering, doc_id, user_id, returned_user_id, agreed_datetime, comment, decision_type, final_user, cur_user) VALUES (100083, 2, 100063, 4329, null, '2019-10-21 12:46:06.629000', '', 'ACCEPTED', true, false);


INSERT INTO esrd.resolution (id, ordering, doc_id, primary_resolution, control_date, execution_datetime, department_id) VALUES (100018, 2, 100000, false, null, null, 579);
INSERT INTO esrd.resolution (id, ordering, doc_id, primary_resolution, control_date, execution_datetime, department_id) VALUES (100039, 2, 100021, false, null, null, 579);
INSERT INTO esrd.resolution (id, ordering, doc_id, primary_resolution, control_date, execution_datetime, department_id) VALUES (100060, 2, 100042, false, null, null, 579);
INSERT INTO esrd.resolution (id, ordering, doc_id, primary_resolution, control_date, execution_datetime, department_id) VALUES (100081, 2, 100063, false, null, null, 579);
INSERT INTO esrd.resolution (id, ordering, doc_id, primary_resolution, control_date, execution_datetime, department_id) VALUES (100101, 1, 100084, true, null, null, 575);
INSERT INTO esrd.resolution (id, ordering, doc_id, primary_resolution, control_date, execution_datetime, department_id) VALUES (100102, 2, 100084, false, null, null, 579);
INSERT INTO esrd.resolution (id, ordering, doc_id, primary_resolution, control_date, execution_datetime, department_id) VALUES (100122, 1, 100105, true, null, null, 575);
INSERT INTO esrd.resolution (id, ordering, doc_id, primary_resolution, control_date, execution_datetime, department_id) VALUES (100123, 2, 100105, false, null, null, 579);
INSERT INTO esrd.resolution (id, ordering, doc_id, primary_resolution, control_date, execution_datetime, department_id) VALUES (100017, 1, 100000, true, '2019-10-23', null, 575);
INSERT INTO esrd.resolution (id, ordering, doc_id, primary_resolution, control_date, execution_datetime, department_id) VALUES (100038, 1, 100021, true, '2019-10-27', null, 575);
INSERT INTO esrd.resolution (id, ordering, doc_id, primary_resolution, control_date, execution_datetime, department_id) VALUES (100059, 1, 100042, true, '2019-10-27', '2019-10-26', 575);
INSERT INTO esrd.resolution (id, ordering, doc_id, primary_resolution, control_date, execution_datetime, department_id) VALUES (100239, 1, 100222, true, null, null, 575);
INSERT INTO esrd.resolution (id, ordering, doc_id, primary_resolution, control_date, execution_datetime, department_id) VALUES (100240, 2, 100222, false, null, null, 579);
INSERT INTO esrd.resolution (id, ordering, doc_id, primary_resolution, control_date, execution_datetime, department_id) VALUES (100080, 1, 100063, true, '2019-10-23', null, 575);

INSERT INTO esrd.resolutions_users (id, resolution_datetime, user_id, resolution_id) VALUES (100243, '2019-10-21 12:45:06.018000', 4373, 100017);
INSERT INTO esrd.resolutions_users (id, resolution_datetime, user_id, resolution_id) VALUES (100244, '2019-10-21 12:45:18.874000', 4373, 100038);
INSERT INTO esrd.resolutions_users (id, resolution_datetime, user_id, resolution_id) VALUES (100245, '2019-10-21 12:45:27.967000', 4373, 100059);

INSERT INTO esrd.users_distribution_departments (user_id, distribution_departments_id) VALUES (4084, 575);
INSERT INTO esrd.users_distribution_departments (user_id, distribution_departments_id) VALUES (4373, 575);