package ru.gbuac.model;

public enum FieldType {
    TEXT,
    TEXTAREA,
    NUMBER,
    DATE,
    TIME,
    DATETIME,
    CATALOG_ADDABLE,
    CATALOG,
    CATALOG_MULTI_SELECT,
    GROUP_FIELDS,
    GROUP_CHECKBOX,
    CHECKBOX,
    ATTACHMENT,
    CATALOG_USERS,
    CATALOG_ORGANIZATIONS,
    CATALOG_REGNUMBERS,
    CATALOG_HTML_TABLES
}
